name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.manifest-release.outputs.paths_released }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: manifest-release
        with:
          command: manifest
