name: "Release Please"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.manifest-release.outputs.paths_released }}
      releases_created: ${{ steps.manifest-release.outputs.releases_created }}

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ''

      - uses: google-github-actions/release-please-action@v4
        id: manifest-release
        with:
          manifest-file: .release-please-manifest.json

      - name: Show output from Release-Please
        run: |
          echo "RELEASES_created: ${{ steps.manifest-release.outputs.releases_created }}"
          echo "paths_released: ${{ steps.manifest-release.outputs.paths_released }}"

  release-packages:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    strategy:
      matrix:
        path: ${{ fromJSON(needs.release-please.outputs.paths_released) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure user
        run: |
          git config user.name "Automation Bot"
          git config user.email "ju.skinner@gmail.com"

      - uses: bhowell2/github-substring-action@1.0.2
        id: project-name
        with:
          value: ${{ matrix.path}}
          index_of_str: "libs/"

      - name: Build Packages
        run: npm install --legacy-peer-deps

      - uses: ./.github/workflows/actions/publish-npm
        with:
          tag: 'latest'
          token: ${{ secrets.NPM_TOKEN }}
          working-directory: ${{ matrix.path }}
          project: "sw-${{ steps.project-name.outputs.substring }}"
